POST http://localhost:4500/notebook
Content-Type: application/json

{
    "noteTitle": "Note 1",
    "noteContent": "This is the note content",
    "createdAt": "2023-06-05 04:38:56.157"
}

###
GET http://localhost:4500/notebook

###
GET http://localhost:4500/notebook/1e69513a-d8ec-4ced-8fe2-f5201112245

### UPDATING PROJECT
PUT http://localhost:4500/notebook/c6f72868-bf02-44f2-860c-08f02f906b82
Content-Type: application/json

{
    "noteTitle": "Note 1 ii",
    "noteContent": "This is the note content",
    "createdAt": "2023-06-05 04:38:56.157"
}

###
DELETE http://localhost:4500/notebook/c6f72868-bf02-44f2-860c-08f02f906b82